// src/components/HeaderNavigation.tsx
"use client";

import HeaderLogo from "@/components/HeaderLogo";
import Link from "next/link";
import { useState } from "react";

export default function HeaderNavigation() {
  const [open, setOpen] = useState(false);

  function openMenu() {
    setOpen(!open);
  }

  const navOpened = open ? "header open" : "header";
  return (
    <div className={navOpened}>
      <HeaderLogo />
      <nav>
        <div className="nav-elem">
          <Link href={"/"}>Galerie</Link>
        </div>
        <div className="nav-elem">
          <Link href={"/covers"}>Couvertures</Link>
        </div>
        <div className="nav-elem">
          <Link href={"/cards"}>Cartes</Link>
        </div>
        <div className="nav-elem">
          <Link href={"/contact"}>Contact</Link>
        </div>
      </nav>
      <button className={"menu"} onClick={openMenu}>
        <div />
        <div />
        <div />
      </button>
    </div>
  );
}

// node/client/src/components/HeaderNavigation.vue
<template>
  <div
    :class="{open:opened}"
    class="header"
  >
    <HeaderLogo />
    <nav>
      <div class="nav-elem">
        <router-link :to="{name:'Gallery',params:{id:0}}">
          Galerie
        </router-link>
      </div>
      <div class="nav-elem">
        <router-link :to="{name:'Book Cover'}">
          Couvertures
        </router-link>
      </div>
      <div class="nav-elem">
        <router-link :to="{name:'Cartes'}">
          Cartes
        </router-link>
      </div>
      <div class="nav-elem">
        <router-link :to="{name:'Contact'}">
          Contact
        </router-link>
      </div>
    </nav>
    <div
      class="menu"
      @click="open"
    >
      <div />
      <div />
      <div />
    </div>
  </div>
</template>

<script lang="ts" setup>
import HeaderLogo from '@/components/HeaderLogo.vue';
import { ref } from 'vue';


const opened = ref(false);
const open = () => {
	opened.value = !opened.value;
};
</script>

<style scoped></style>
